version: '3.8'

services:
 db:
  image: postgres:15
  container_name: osl-registration-database
  environment:
   POSTGRES_USER: osl
   POSTGRES_PASSWORD: osl123
   POSTGRES_DB: osl-registration
  ports:
   - "5432:5432"
  volumes:
   - db-data:/var/lib/postgresql/data

volumes:
 db-data:
  driver: local